/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as NuestrosCursosImport } from './routes/nuestros-cursos'
import { Route as LoginImport } from './routes/login'
import { Route as InfoCatraImport } from './routes/info-catra'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthPerfilImport } from './routes/_auth/perfil'
import { Route as AuthDashboardImport } from './routes/_auth/dashboard'
import { Route as AuthSeleccionCursoImport } from './routes/_auth/Seleccion-Curso'
import { Route as AuthListaDistribucionImport } from './routes/_auth/Lista-Distribucion'
import { Route as AuthListaCursosImport } from './routes/_auth/Lista-Cursos'
import { Route as AuthUsuariosRouteImport } from './routes/_auth/usuarios/route'
import { Route as AuthClientesRouteImport } from './routes/_auth/clientes/route'
import { Route as AuthClienteRouteImport } from './routes/_auth/_cliente/route'
import { Route as AuthAdminRouteImport } from './routes/_auth/_admin/route'
import { Route as AuthValidarDocumentosIndexImport } from './routes/_auth/validar-documentos/index'
import { Route as AuthUsuariosIndexImport } from './routes/_auth/usuarios/index'
import { Route as AuthExamenesIndexImport } from './routes/_auth/examenes/index'
import { Route as AuthClientesIndexImport } from './routes/_auth/clientes/index'
import { Route as AuthValidarDocumentosUserIdImport } from './routes/_auth/validar-documentos/$userId'
import { Route as AuthUsuariosCrearImport } from './routes/_auth/usuarios/crear'
import { Route as AuthExamenesDisponiblesImport } from './routes/_auth/examenes/disponibles'
import { Route as AuthExamenesCreateImport } from './routes/_auth/examenes/create'
import { Route as AuthClientesCrearImport } from './routes/_auth/clientes/crear'
import { Route as AuthClienteSubirDocumentosImport } from './routes/_auth/_cliente/subir-documentos'
import { Route as AuthClienteRealizarExamenImport } from './routes/_auth/_cliente/realizar-examen'
import { Route as AuthAdminSoloAdminImport } from './routes/_auth/_admin/solo-admin'
import { Route as AuthUsuariosEditarUserIdImport } from './routes/_auth/usuarios/editar.$userId'
import { Route as AuthExamenesExamenIdRealizarImport } from './routes/_auth/examenes/$examenId/realizar'
import { Route as AuthExamenesExamenIdEditImport } from './routes/_auth/examenes/$examenId/edit'
import { Route as AuthClientesEditarCurpImport } from './routes/_auth/clientes/editar.$curp'
import { Route as AuthExamenesExamenIdPreguntasIndexImport } from './routes/_auth/examenes/$examenId/preguntas/index'
import { Route as AuthExamenesExamenIdPreguntasCreateImport } from './routes/_auth/examenes/$examenId/preguntas/create'
import { Route as AuthExamenesExamenIdPreguntasPreguntaIdEditImport } from './routes/_auth/examenes/$examenId/preguntas/$preguntaId/edit'
import { Route as AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexImport } from './routes/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/index'
import { Route as AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateImport } from './routes/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
import { Route as AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditImport } from './routes/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId.edit'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const NuestrosCursosRoute = NuestrosCursosImport.update({
  id: '/nuestros-cursos',
  path: '/nuestros-cursos',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InfoCatraRoute = InfoCatraImport.update({
  id: '/info-catra',
  path: '/info-catra',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPerfilRoute = AuthPerfilImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthDashboardRoute = AuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthSeleccionCursoRoute = AuthSeleccionCursoImport.update({
  id: '/Seleccion-Curso',
  path: '/Seleccion-Curso',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthListaDistribucionRoute = AuthListaDistribucionImport.update({
  id: '/Lista-Distribucion',
  path: '/Lista-Distribucion',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthListaCursosRoute = AuthListaCursosImport.update({
  id: '/Lista-Cursos',
  path: '/Lista-Cursos',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthUsuariosRouteRoute = AuthUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthClientesRouteRoute = AuthClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthClienteRouteRoute = AuthClienteRouteImport.update({
  id: '/_cliente',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthAdminRouteRoute = AuthAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthValidarDocumentosIndexRoute = AuthValidarDocumentosIndexImport.update(
  {
    id: '/validar-documentos/',
    path: '/validar-documentos/',
    getParentRoute: () => AuthRouteRoute,
  } as any,
)

const AuthUsuariosIndexRoute = AuthUsuariosIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUsuariosRouteRoute,
} as any)

const AuthExamenesIndexRoute = AuthExamenesIndexImport.update({
  id: '/examenes/',
  path: '/examenes/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthClientesIndexRoute = AuthClientesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthClientesRouteRoute,
} as any)

const AuthValidarDocumentosUserIdRoute =
  AuthValidarDocumentosUserIdImport.update({
    id: '/validar-documentos/$userId',
    path: '/validar-documentos/$userId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthUsuariosCrearRoute = AuthUsuariosCrearImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthUsuariosRouteRoute,
} as any)

const AuthExamenesDisponiblesRoute = AuthExamenesDisponiblesImport.update({
  id: '/examenes/disponibles',
  path: '/examenes/disponibles',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthExamenesCreateRoute = AuthExamenesCreateImport.update({
  id: '/examenes/create',
  path: '/examenes/create',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthClientesCrearRoute = AuthClientesCrearImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthClientesRouteRoute,
} as any)

const AuthClienteSubirDocumentosRoute = AuthClienteSubirDocumentosImport.update(
  {
    id: '/subir-documentos',
    path: '/subir-documentos',
    getParentRoute: () => AuthClienteRouteRoute,
  } as any,
)

const AuthClienteRealizarExamenRoute = AuthClienteRealizarExamenImport.update({
  id: '/realizar-examen',
  path: '/realizar-examen',
  getParentRoute: () => AuthClienteRouteRoute,
} as any)

const AuthAdminSoloAdminRoute = AuthAdminSoloAdminImport.update({
  id: '/solo-admin',
  path: '/solo-admin',
  getParentRoute: () => AuthAdminRouteRoute,
} as any)

const AuthUsuariosEditarUserIdRoute = AuthUsuariosEditarUserIdImport.update({
  id: '/editar/$userId',
  path: '/editar/$userId',
  getParentRoute: () => AuthUsuariosRouteRoute,
} as any)

const AuthExamenesExamenIdRealizarRoute =
  AuthExamenesExamenIdRealizarImport.update({
    id: '/examenes/$examenId/realizar',
    path: '/examenes/$examenId/realizar',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdEditRoute = AuthExamenesExamenIdEditImport.update({
  id: '/examenes/$examenId/edit',
  path: '/examenes/$examenId/edit',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthClientesEditarCurpRoute = AuthClientesEditarCurpImport.update({
  id: '/editar/$curp',
  path: '/editar/$curp',
  getParentRoute: () => AuthClientesRouteRoute,
} as any)

const AuthExamenesExamenIdPreguntasIndexRoute =
  AuthExamenesExamenIdPreguntasIndexImport.update({
    id: '/examenes/$examenId/preguntas/',
    path: '/examenes/$examenId/preguntas/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdPreguntasCreateRoute =
  AuthExamenesExamenIdPreguntasCreateImport.update({
    id: '/examenes/$examenId/preguntas/create',
    path: '/examenes/$examenId/preguntas/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdPreguntasPreguntaIdEditRoute =
  AuthExamenesExamenIdPreguntasPreguntaIdEditImport.update({
    id: '/examenes/$examenId/preguntas/$preguntaId/edit',
    path: '/examenes/$examenId/preguntas/$preguntaId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute =
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexImport.update({
    id: '/examenes/$examenId/preguntas/$preguntaId/respuestas/',
    path: '/examenes/$examenId/preguntas/$preguntaId/respuestas/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute =
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateImport.update({
    id: '/examenes/$examenId/preguntas/$preguntaId/respuestas/create',
    path: '/examenes/$examenId/preguntas/$preguntaId/respuestas/create',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute =
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditImport.update(
    {
      id: '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit',
      path: '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit',
      getParentRoute: () => AuthRouteRoute,
    } as any,
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/info-catra': {
      id: '/info-catra'
      path: '/info-catra'
      fullPath: '/info-catra'
      preLoaderRoute: typeof InfoCatraImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/nuestros-cursos': {
      id: '/nuestros-cursos'
      path: '/nuestros-cursos'
      fullPath: '/nuestros-cursos'
      preLoaderRoute: typeof NuestrosCursosImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/_cliente': {
      id: '/_auth/_cliente'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthClienteRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/clientes': {
      id: '/_auth/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthClientesRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios': {
      id: '/_auth/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthUsuariosRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/Lista-Cursos': {
      id: '/_auth/Lista-Cursos'
      path: '/Lista-Cursos'
      fullPath: '/Lista-Cursos'
      preLoaderRoute: typeof AuthListaCursosImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/Lista-Distribucion': {
      id: '/_auth/Lista-Distribucion'
      path: '/Lista-Distribucion'
      fullPath: '/Lista-Distribucion'
      preLoaderRoute: typeof AuthListaDistribucionImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/Seleccion-Curso': {
      id: '/_auth/Seleccion-Curso'
      path: '/Seleccion-Curso'
      fullPath: '/Seleccion-Curso'
      preLoaderRoute: typeof AuthSeleccionCursoImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/perfil': {
      id: '/_auth/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthPerfilImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/_admin/solo-admin': {
      id: '/_auth/_admin/solo-admin'
      path: '/solo-admin'
      fullPath: '/solo-admin'
      preLoaderRoute: typeof AuthAdminSoloAdminImport
      parentRoute: typeof AuthAdminRouteImport
    }
    '/_auth/_cliente/realizar-examen': {
      id: '/_auth/_cliente/realizar-examen'
      path: '/realizar-examen'
      fullPath: '/realizar-examen'
      preLoaderRoute: typeof AuthClienteRealizarExamenImport
      parentRoute: typeof AuthClienteRouteImport
    }
    '/_auth/_cliente/subir-documentos': {
      id: '/_auth/_cliente/subir-documentos'
      path: '/subir-documentos'
      fullPath: '/subir-documentos'
      preLoaderRoute: typeof AuthClienteSubirDocumentosImport
      parentRoute: typeof AuthClienteRouteImport
    }
    '/_auth/clientes/crear': {
      id: '/_auth/clientes/crear'
      path: '/crear'
      fullPath: '/clientes/crear'
      preLoaderRoute: typeof AuthClientesCrearImport
      parentRoute: typeof AuthClientesRouteImport
    }
    '/_auth/examenes/create': {
      id: '/_auth/examenes/create'
      path: '/examenes/create'
      fullPath: '/examenes/create'
      preLoaderRoute: typeof AuthExamenesCreateImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/disponibles': {
      id: '/_auth/examenes/disponibles'
      path: '/examenes/disponibles'
      fullPath: '/examenes/disponibles'
      preLoaderRoute: typeof AuthExamenesDisponiblesImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios/crear': {
      id: '/_auth/usuarios/crear'
      path: '/crear'
      fullPath: '/usuarios/crear'
      preLoaderRoute: typeof AuthUsuariosCrearImport
      parentRoute: typeof AuthUsuariosRouteImport
    }
    '/_auth/validar-documentos/$userId': {
      id: '/_auth/validar-documentos/$userId'
      path: '/validar-documentos/$userId'
      fullPath: '/validar-documentos/$userId'
      preLoaderRoute: typeof AuthValidarDocumentosUserIdImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/clientes/': {
      id: '/_auth/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthClientesIndexImport
      parentRoute: typeof AuthClientesRouteImport
    }
    '/_auth/examenes/': {
      id: '/_auth/examenes/'
      path: '/examenes'
      fullPath: '/examenes'
      preLoaderRoute: typeof AuthExamenesIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios/': {
      id: '/_auth/usuarios/'
      path: '/'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthUsuariosIndexImport
      parentRoute: typeof AuthUsuariosRouteImport
    }
    '/_auth/validar-documentos/': {
      id: '/_auth/validar-documentos/'
      path: '/validar-documentos'
      fullPath: '/validar-documentos'
      preLoaderRoute: typeof AuthValidarDocumentosIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/clientes/editar/$curp': {
      id: '/_auth/clientes/editar/$curp'
      path: '/editar/$curp'
      fullPath: '/clientes/editar/$curp'
      preLoaderRoute: typeof AuthClientesEditarCurpImport
      parentRoute: typeof AuthClientesRouteImport
    }
    '/_auth/examenes/$examenId/edit': {
      id: '/_auth/examenes/$examenId/edit'
      path: '/examenes/$examenId/edit'
      fullPath: '/examenes/$examenId/edit'
      preLoaderRoute: typeof AuthExamenesExamenIdEditImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/realizar': {
      id: '/_auth/examenes/$examenId/realizar'
      path: '/examenes/$examenId/realizar'
      fullPath: '/examenes/$examenId/realizar'
      preLoaderRoute: typeof AuthExamenesExamenIdRealizarImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/usuarios/editar/$userId': {
      id: '/_auth/usuarios/editar/$userId'
      path: '/editar/$userId'
      fullPath: '/usuarios/editar/$userId'
      preLoaderRoute: typeof AuthUsuariosEditarUserIdImport
      parentRoute: typeof AuthUsuariosRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/create': {
      id: '/_auth/examenes/$examenId/preguntas/create'
      path: '/examenes/$examenId/preguntas/create'
      fullPath: '/examenes/$examenId/preguntas/create'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasCreateImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/': {
      id: '/_auth/examenes/$examenId/preguntas/'
      path: '/examenes/$examenId/preguntas'
      fullPath: '/examenes/$examenId/preguntas'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/$preguntaId/edit': {
      id: '/_auth/examenes/$examenId/preguntas/$preguntaId/edit'
      path: '/examenes/$examenId/preguntas/$preguntaId/edit'
      fullPath: '/examenes/$examenId/preguntas/$preguntaId/edit'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdEditImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create': {
      id: '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
      path: '/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
      fullPath: '/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/': {
      id: '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/'
      path: '/examenes/$examenId/preguntas/$preguntaId/respuestas'
      fullPath: '/examenes/$examenId/preguntas/$preguntaId/respuestas'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit': {
      id: '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
      path: '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
      fullPath: '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
      preLoaderRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AuthAdminRouteRouteChildren {
  AuthAdminSoloAdminRoute: typeof AuthAdminSoloAdminRoute
}

const AuthAdminRouteRouteChildren: AuthAdminRouteRouteChildren = {
  AuthAdminSoloAdminRoute: AuthAdminSoloAdminRoute,
}

const AuthAdminRouteRouteWithChildren = AuthAdminRouteRoute._addFileChildren(
  AuthAdminRouteRouteChildren,
)

interface AuthClienteRouteRouteChildren {
  AuthClienteRealizarExamenRoute: typeof AuthClienteRealizarExamenRoute
  AuthClienteSubirDocumentosRoute: typeof AuthClienteSubirDocumentosRoute
}

const AuthClienteRouteRouteChildren: AuthClienteRouteRouteChildren = {
  AuthClienteRealizarExamenRoute: AuthClienteRealizarExamenRoute,
  AuthClienteSubirDocumentosRoute: AuthClienteSubirDocumentosRoute,
}

const AuthClienteRouteRouteWithChildren =
  AuthClienteRouteRoute._addFileChildren(AuthClienteRouteRouteChildren)

interface AuthClientesRouteRouteChildren {
  AuthClientesCrearRoute: typeof AuthClientesCrearRoute
  AuthClientesIndexRoute: typeof AuthClientesIndexRoute
  AuthClientesEditarCurpRoute: typeof AuthClientesEditarCurpRoute
}

const AuthClientesRouteRouteChildren: AuthClientesRouteRouteChildren = {
  AuthClientesCrearRoute: AuthClientesCrearRoute,
  AuthClientesIndexRoute: AuthClientesIndexRoute,
  AuthClientesEditarCurpRoute: AuthClientesEditarCurpRoute,
}

const AuthClientesRouteRouteWithChildren =
  AuthClientesRouteRoute._addFileChildren(AuthClientesRouteRouteChildren)

interface AuthUsuariosRouteRouteChildren {
  AuthUsuariosCrearRoute: typeof AuthUsuariosCrearRoute
  AuthUsuariosIndexRoute: typeof AuthUsuariosIndexRoute
  AuthUsuariosEditarUserIdRoute: typeof AuthUsuariosEditarUserIdRoute
}

const AuthUsuariosRouteRouteChildren: AuthUsuariosRouteRouteChildren = {
  AuthUsuariosCrearRoute: AuthUsuariosCrearRoute,
  AuthUsuariosIndexRoute: AuthUsuariosIndexRoute,
  AuthUsuariosEditarUserIdRoute: AuthUsuariosEditarUserIdRoute,
}

const AuthUsuariosRouteRouteWithChildren =
  AuthUsuariosRouteRoute._addFileChildren(AuthUsuariosRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAdminRouteRoute: typeof AuthAdminRouteRouteWithChildren
  AuthClienteRouteRoute: typeof AuthClienteRouteRouteWithChildren
  AuthClientesRouteRoute: typeof AuthClientesRouteRouteWithChildren
  AuthUsuariosRouteRoute: typeof AuthUsuariosRouteRouteWithChildren
  AuthListaCursosRoute: typeof AuthListaCursosRoute
  AuthListaDistribucionRoute: typeof AuthListaDistribucionRoute
  AuthSeleccionCursoRoute: typeof AuthSeleccionCursoRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthPerfilRoute: typeof AuthPerfilRoute
  AuthExamenesCreateRoute: typeof AuthExamenesCreateRoute
  AuthExamenesDisponiblesRoute: typeof AuthExamenesDisponiblesRoute
  AuthValidarDocumentosUserIdRoute: typeof AuthValidarDocumentosUserIdRoute
  AuthExamenesIndexRoute: typeof AuthExamenesIndexRoute
  AuthValidarDocumentosIndexRoute: typeof AuthValidarDocumentosIndexRoute
  AuthExamenesExamenIdEditRoute: typeof AuthExamenesExamenIdEditRoute
  AuthExamenesExamenIdRealizarRoute: typeof AuthExamenesExamenIdRealizarRoute
  AuthExamenesExamenIdPreguntasCreateRoute: typeof AuthExamenesExamenIdPreguntasCreateRoute
  AuthExamenesExamenIdPreguntasIndexRoute: typeof AuthExamenesExamenIdPreguntasIndexRoute
  AuthExamenesExamenIdPreguntasPreguntaIdEditRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdEditRoute
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute: typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminRouteRoute: AuthAdminRouteRouteWithChildren,
  AuthClienteRouteRoute: AuthClienteRouteRouteWithChildren,
  AuthClientesRouteRoute: AuthClientesRouteRouteWithChildren,
  AuthUsuariosRouteRoute: AuthUsuariosRouteRouteWithChildren,
  AuthListaCursosRoute: AuthListaCursosRoute,
  AuthListaDistribucionRoute: AuthListaDistribucionRoute,
  AuthSeleccionCursoRoute: AuthSeleccionCursoRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthPerfilRoute: AuthPerfilRoute,
  AuthExamenesCreateRoute: AuthExamenesCreateRoute,
  AuthExamenesDisponiblesRoute: AuthExamenesDisponiblesRoute,
  AuthValidarDocumentosUserIdRoute: AuthValidarDocumentosUserIdRoute,
  AuthExamenesIndexRoute: AuthExamenesIndexRoute,
  AuthValidarDocumentosIndexRoute: AuthValidarDocumentosIndexRoute,
  AuthExamenesExamenIdEditRoute: AuthExamenesExamenIdEditRoute,
  AuthExamenesExamenIdRealizarRoute: AuthExamenesExamenIdRealizarRoute,
  AuthExamenesExamenIdPreguntasCreateRoute:
    AuthExamenesExamenIdPreguntasCreateRoute,
  AuthExamenesExamenIdPreguntasIndexRoute:
    AuthExamenesExamenIdPreguntasIndexRoute,
  AuthExamenesExamenIdPreguntasPreguntaIdEditRoute:
    AuthExamenesExamenIdPreguntasPreguntaIdEditRoute,
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute:
    AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute,
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute:
    AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute,
  AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute:
    AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthClienteRouteRouteWithChildren
  '/info-catra': typeof InfoCatraRoute
  '/login': typeof LoginRoute
  '/nuestros-cursos': typeof NuestrosCursosRoute
  '/signup': typeof SignupRoute
  '/clientes': typeof AuthClientesRouteRouteWithChildren
  '/usuarios': typeof AuthUsuariosRouteRouteWithChildren
  '/Lista-Cursos': typeof AuthListaCursosRoute
  '/Lista-Distribucion': typeof AuthListaDistribucionRoute
  '/Seleccion-Curso': typeof AuthSeleccionCursoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/perfil': typeof AuthPerfilRoute
  '/solo-admin': typeof AuthAdminSoloAdminRoute
  '/realizar-examen': typeof AuthClienteRealizarExamenRoute
  '/subir-documentos': typeof AuthClienteSubirDocumentosRoute
  '/clientes/crear': typeof AuthClientesCrearRoute
  '/examenes/create': typeof AuthExamenesCreateRoute
  '/examenes/disponibles': typeof AuthExamenesDisponiblesRoute
  '/usuarios/crear': typeof AuthUsuariosCrearRoute
  '/validar-documentos/$userId': typeof AuthValidarDocumentosUserIdRoute
  '/clientes/': typeof AuthClientesIndexRoute
  '/examenes': typeof AuthExamenesIndexRoute
  '/usuarios/': typeof AuthUsuariosIndexRoute
  '/validar-documentos': typeof AuthValidarDocumentosIndexRoute
  '/clientes/editar/$curp': typeof AuthClientesEditarCurpRoute
  '/examenes/$examenId/edit': typeof AuthExamenesExamenIdEditRoute
  '/examenes/$examenId/realizar': typeof AuthExamenesExamenIdRealizarRoute
  '/usuarios/editar/$userId': typeof AuthUsuariosEditarUserIdRoute
  '/examenes/$examenId/preguntas/create': typeof AuthExamenesExamenIdPreguntasCreateRoute
  '/examenes/$examenId/preguntas': typeof AuthExamenesExamenIdPreguntasIndexRoute
  '/examenes/$examenId/preguntas/$preguntaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdEditRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas/create': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthClienteRouteRouteWithChildren
  '/info-catra': typeof InfoCatraRoute
  '/login': typeof LoginRoute
  '/nuestros-cursos': typeof NuestrosCursosRoute
  '/signup': typeof SignupRoute
  '/Lista-Cursos': typeof AuthListaCursosRoute
  '/Lista-Distribucion': typeof AuthListaDistribucionRoute
  '/Seleccion-Curso': typeof AuthSeleccionCursoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/perfil': typeof AuthPerfilRoute
  '/solo-admin': typeof AuthAdminSoloAdminRoute
  '/realizar-examen': typeof AuthClienteRealizarExamenRoute
  '/subir-documentos': typeof AuthClienteSubirDocumentosRoute
  '/clientes/crear': typeof AuthClientesCrearRoute
  '/examenes/create': typeof AuthExamenesCreateRoute
  '/examenes/disponibles': typeof AuthExamenesDisponiblesRoute
  '/usuarios/crear': typeof AuthUsuariosCrearRoute
  '/validar-documentos/$userId': typeof AuthValidarDocumentosUserIdRoute
  '/clientes': typeof AuthClientesIndexRoute
  '/examenes': typeof AuthExamenesIndexRoute
  '/usuarios': typeof AuthUsuariosIndexRoute
  '/validar-documentos': typeof AuthValidarDocumentosIndexRoute
  '/clientes/editar/$curp': typeof AuthClientesEditarCurpRoute
  '/examenes/$examenId/edit': typeof AuthExamenesExamenIdEditRoute
  '/examenes/$examenId/realizar': typeof AuthExamenesExamenIdRealizarRoute
  '/usuarios/editar/$userId': typeof AuthUsuariosEditarUserIdRoute
  '/examenes/$examenId/preguntas/create': typeof AuthExamenesExamenIdPreguntasCreateRoute
  '/examenes/$examenId/preguntas': typeof AuthExamenesExamenIdPreguntasIndexRoute
  '/examenes/$examenId/preguntas/$preguntaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdEditRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas/create': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute
  '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/info-catra': typeof InfoCatraRoute
  '/login': typeof LoginRoute
  '/nuestros-cursos': typeof NuestrosCursosRoute
  '/signup': typeof SignupRoute
  '/_auth/_admin': typeof AuthAdminRouteRouteWithChildren
  '/_auth/_cliente': typeof AuthClienteRouteRouteWithChildren
  '/_auth/clientes': typeof AuthClientesRouteRouteWithChildren
  '/_auth/usuarios': typeof AuthUsuariosRouteRouteWithChildren
  '/_auth/Lista-Cursos': typeof AuthListaCursosRoute
  '/_auth/Lista-Distribucion': typeof AuthListaDistribucionRoute
  '/_auth/Seleccion-Curso': typeof AuthSeleccionCursoRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/perfil': typeof AuthPerfilRoute
  '/_auth/_admin/solo-admin': typeof AuthAdminSoloAdminRoute
  '/_auth/_cliente/realizar-examen': typeof AuthClienteRealizarExamenRoute
  '/_auth/_cliente/subir-documentos': typeof AuthClienteSubirDocumentosRoute
  '/_auth/clientes/crear': typeof AuthClientesCrearRoute
  '/_auth/examenes/create': typeof AuthExamenesCreateRoute
  '/_auth/examenes/disponibles': typeof AuthExamenesDisponiblesRoute
  '/_auth/usuarios/crear': typeof AuthUsuariosCrearRoute
  '/_auth/validar-documentos/$userId': typeof AuthValidarDocumentosUserIdRoute
  '/_auth/clientes/': typeof AuthClientesIndexRoute
  '/_auth/examenes/': typeof AuthExamenesIndexRoute
  '/_auth/usuarios/': typeof AuthUsuariosIndexRoute
  '/_auth/validar-documentos/': typeof AuthValidarDocumentosIndexRoute
  '/_auth/clientes/editar/$curp': typeof AuthClientesEditarCurpRoute
  '/_auth/examenes/$examenId/edit': typeof AuthExamenesExamenIdEditRoute
  '/_auth/examenes/$examenId/realizar': typeof AuthExamenesExamenIdRealizarRoute
  '/_auth/usuarios/editar/$userId': typeof AuthUsuariosEditarUserIdRoute
  '/_auth/examenes/$examenId/preguntas/create': typeof AuthExamenesExamenIdPreguntasCreateRoute
  '/_auth/examenes/$examenId/preguntas/': typeof AuthExamenesExamenIdPreguntasIndexRoute
  '/_auth/examenes/$examenId/preguntas/$preguntaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdEditRoute
  '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasCreateRoute
  '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasIndexRoute
  '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit': typeof AuthExamenesExamenIdPreguntasPreguntaIdRespuestasRespuestaIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/info-catra'
    | '/login'
    | '/nuestros-cursos'
    | '/signup'
    | '/clientes'
    | '/usuarios'
    | '/Lista-Cursos'
    | '/Lista-Distribucion'
    | '/Seleccion-Curso'
    | '/dashboard'
    | '/perfil'
    | '/solo-admin'
    | '/realizar-examen'
    | '/subir-documentos'
    | '/clientes/crear'
    | '/examenes/create'
    | '/examenes/disponibles'
    | '/usuarios/crear'
    | '/validar-documentos/$userId'
    | '/clientes/'
    | '/examenes'
    | '/usuarios/'
    | '/validar-documentos'
    | '/clientes/editar/$curp'
    | '/examenes/$examenId/edit'
    | '/examenes/$examenId/realizar'
    | '/usuarios/editar/$userId'
    | '/examenes/$examenId/preguntas/create'
    | '/examenes/$examenId/preguntas'
    | '/examenes/$examenId/preguntas/$preguntaId/edit'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/info-catra'
    | '/login'
    | '/nuestros-cursos'
    | '/signup'
    | '/Lista-Cursos'
    | '/Lista-Distribucion'
    | '/Seleccion-Curso'
    | '/dashboard'
    | '/perfil'
    | '/solo-admin'
    | '/realizar-examen'
    | '/subir-documentos'
    | '/clientes/crear'
    | '/examenes/create'
    | '/examenes/disponibles'
    | '/usuarios/crear'
    | '/validar-documentos/$userId'
    | '/clientes'
    | '/examenes'
    | '/usuarios'
    | '/validar-documentos'
    | '/clientes/editar/$curp'
    | '/examenes/$examenId/edit'
    | '/examenes/$examenId/realizar'
    | '/usuarios/editar/$userId'
    | '/examenes/$examenId/preguntas/create'
    | '/examenes/$examenId/preguntas'
    | '/examenes/$examenId/preguntas/$preguntaId/edit'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas'
    | '/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/info-catra'
    | '/login'
    | '/nuestros-cursos'
    | '/signup'
    | '/_auth/_admin'
    | '/_auth/_cliente'
    | '/_auth/clientes'
    | '/_auth/usuarios'
    | '/_auth/Lista-Cursos'
    | '/_auth/Lista-Distribucion'
    | '/_auth/Seleccion-Curso'
    | '/_auth/dashboard'
    | '/_auth/perfil'
    | '/_auth/_admin/solo-admin'
    | '/_auth/_cliente/realizar-examen'
    | '/_auth/_cliente/subir-documentos'
    | '/_auth/clientes/crear'
    | '/_auth/examenes/create'
    | '/_auth/examenes/disponibles'
    | '/_auth/usuarios/crear'
    | '/_auth/validar-documentos/$userId'
    | '/_auth/clientes/'
    | '/_auth/examenes/'
    | '/_auth/usuarios/'
    | '/_auth/validar-documentos/'
    | '/_auth/clientes/editar/$curp'
    | '/_auth/examenes/$examenId/edit'
    | '/_auth/examenes/$examenId/realizar'
    | '/_auth/usuarios/editar/$userId'
    | '/_auth/examenes/$examenId/preguntas/create'
    | '/_auth/examenes/$examenId/preguntas/'
    | '/_auth/examenes/$examenId/preguntas/$preguntaId/edit'
    | '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create'
    | '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/'
    | '/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  InfoCatraRoute: typeof InfoCatraRoute
  LoginRoute: typeof LoginRoute
  NuestrosCursosRoute: typeof NuestrosCursosRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  InfoCatraRoute: InfoCatraRoute,
  LoginRoute: LoginRoute,
  NuestrosCursosRoute: NuestrosCursosRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_auth",
        "/info-catra",
        "/login",
        "/nuestros-cursos",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_auth": {
      "filePath": "_auth/route.jsx",
      "children": [
        "/_auth/_admin",
        "/_auth/_cliente",
        "/_auth/clientes",
        "/_auth/usuarios",
        "/_auth/Lista-Cursos",
        "/_auth/Lista-Distribucion",
        "/_auth/Seleccion-Curso",
        "/_auth/dashboard",
        "/_auth/perfil",
        "/_auth/examenes/create",
        "/_auth/examenes/disponibles",
        "/_auth/validar-documentos/$userId",
        "/_auth/examenes/",
        "/_auth/validar-documentos/",
        "/_auth/examenes/$examenId/edit",
        "/_auth/examenes/$examenId/realizar",
        "/_auth/examenes/$examenId/preguntas/create",
        "/_auth/examenes/$examenId/preguntas/",
        "/_auth/examenes/$examenId/preguntas/$preguntaId/edit",
        "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create",
        "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/",
        "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit"
      ]
    },
    "/info-catra": {
      "filePath": "info-catra.jsx"
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/nuestros-cursos": {
      "filePath": "nuestros-cursos.jsx"
    },
    "/signup": {
      "filePath": "signup.jsx"
    },
    "/_auth/_admin": {
      "filePath": "_auth/_admin/route.jsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_admin/solo-admin"
      ]
    },
    "/_auth/_cliente": {
      "filePath": "_auth/_cliente/route.jsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_cliente/realizar-examen",
        "/_auth/_cliente/subir-documentos"
      ]
    },
    "/_auth/clientes": {
      "filePath": "_auth/clientes/route.jsx",
      "parent": "/_auth",
      "children": [
        "/_auth/clientes/crear",
        "/_auth/clientes/",
        "/_auth/clientes/editar/$curp"
      ]
    },
    "/_auth/usuarios": {
      "filePath": "_auth/usuarios/route.jsx",
      "parent": "/_auth",
      "children": [
        "/_auth/usuarios/crear",
        "/_auth/usuarios/",
        "/_auth/usuarios/editar/$userId"
      ]
    },
    "/_auth/Lista-Cursos": {
      "filePath": "_auth/Lista-Cursos.jsx",
      "parent": "/_auth"
    },
    "/_auth/Lista-Distribucion": {
      "filePath": "_auth/Lista-Distribucion.jsx",
      "parent": "/_auth"
    },
    "/_auth/Seleccion-Curso": {
      "filePath": "_auth/Seleccion-Curso.jsx",
      "parent": "/_auth"
    },
    "/_auth/dashboard": {
      "filePath": "_auth/dashboard.jsx",
      "parent": "/_auth"
    },
    "/_auth/perfil": {
      "filePath": "_auth/perfil.jsx",
      "parent": "/_auth"
    },
    "/_auth/_admin/solo-admin": {
      "filePath": "_auth/_admin/solo-admin.jsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_cliente/realizar-examen": {
      "filePath": "_auth/_cliente/realizar-examen.jsx",
      "parent": "/_auth/_cliente"
    },
    "/_auth/_cliente/subir-documentos": {
      "filePath": "_auth/_cliente/subir-documentos.jsx",
      "parent": "/_auth/_cliente"
    },
    "/_auth/clientes/crear": {
      "filePath": "_auth/clientes/crear.jsx",
      "parent": "/_auth/clientes"
    },
    "/_auth/examenes/create": {
      "filePath": "_auth/examenes/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/disponibles": {
      "filePath": "_auth/examenes/disponibles.jsx",
      "parent": "/_auth"
    },
    "/_auth/usuarios/crear": {
      "filePath": "_auth/usuarios/crear.jsx",
      "parent": "/_auth/usuarios"
    },
    "/_auth/validar-documentos/$userId": {
      "filePath": "_auth/validar-documentos/$userId.jsx",
      "parent": "/_auth"
    },
    "/_auth/clientes/": {
      "filePath": "_auth/clientes/index.jsx",
      "parent": "/_auth/clientes"
    },
    "/_auth/examenes/": {
      "filePath": "_auth/examenes/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/usuarios/": {
      "filePath": "_auth/usuarios/index.jsx",
      "parent": "/_auth/usuarios"
    },
    "/_auth/validar-documentos/": {
      "filePath": "_auth/validar-documentos/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/clientes/editar/$curp": {
      "filePath": "_auth/clientes/editar.$curp.jsx",
      "parent": "/_auth/clientes"
    },
    "/_auth/examenes/$examenId/edit": {
      "filePath": "_auth/examenes/$examenId/edit.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/realizar": {
      "filePath": "_auth/examenes/$examenId/realizar.jsx",
      "parent": "/_auth"
    },
    "/_auth/usuarios/editar/$userId": {
      "filePath": "_auth/usuarios/editar.$userId.jsx",
      "parent": "/_auth/usuarios"
    },
    "/_auth/examenes/$examenId/preguntas/create": {
      "filePath": "_auth/examenes/$examenId/preguntas/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/preguntas/": {
      "filePath": "_auth/examenes/$examenId/preguntas/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/preguntas/$preguntaId/edit": {
      "filePath": "_auth/examenes/$examenId/preguntas/$preguntaId/edit.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create": {
      "filePath": "_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/create.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/": {
      "filePath": "_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/index.jsx",
      "parent": "/_auth"
    },
    "/_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId/edit": {
      "filePath": "_auth/examenes/$examenId/preguntas/$preguntaId/respuestas/$respuestaId.edit.jsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
